best_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from best_shop import settings
from main.views import home, reservation_success
from django.conf.urls.static import static
from account.views import UserLoginView, UserRegistrationView,logout_view
urlpatterns = [
       path('admin/', admin.site.urls),
       path('',home, name='home'),
       path('reservation/', reservation_success ,name='reservation_success'),
       path('login/',UserLoginView.as_view(), name='login'),
       path('register/',UserRegistrationView.as_view(), name='register'),
       path('logout/',logout_view, name='logout'),
       path('manager/', include('manager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import booking_data, booking_confirm


app_name = 'manager'

urlpatterns = [
    path('booking/', booking_data, name='booking'),
    path('booking/<int:pk>/', booking_confirm, name='booking_confirm'),
]

templates/includes/footer.html
<footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
             {{ street }} <br>
                {{ city }}<br>
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Contacts</h4>
            <p>
              <strong>Phone:</strong> {{ phone_number }}<br>
              <strong>Email:</strong> {{ email }}<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
             {{ opening_hours| safe }}
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="{{ instagram }}" class="instagram"><i class="bi bi-instagram"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/yummy-bootstrap-restaurant-website-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>

templates/includes/header.html
 <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-lg-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>MidPoint<span>.</span></h1>
      </a>

      {% include 'includes/nav.html' %}<!-- .navbar -->

      <a class="btn-book-a-table" href="#book-a-table">Передзамовлення</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header>

templates/includes/nav.html
{% load is_manager_tag %}
<nav id="navbar" class="navbar">
    <ul>
        <li><a href="#menu">Головна</a></li>
        <li><a href="#events">Знижки</a></li>
        <li><a href="#gallery">Асортимент</a></li>

        <li><a href="#contact">Контакти</a></li>
        {% if user|is_manager_tag %}
            <li class="dropdown">
                <a href="#"><span>Менеджер</span><i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                    <li><a href="{% url 'manager:booking' %}">Orders</a></li>
                </ul>
            </li>
        {% endif %}
        <li class="dropdown">
            <a href="#">
            <span>
                {% if user.is_authenticated %}
                    {{ user }}
                {% else %}
                    User Account
                {% endif %}
            </span>
            <i class="bi bi-chevron-down dropdown-indicator"></i>
            </a>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'register' %}">Registration</a></li>
                    <li><a href="{% url 'login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
</nav>