best_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from best_shop import settings
from main.views import home, reservation_success
from django.conf.urls.static import static
from account.views import UserLoginView, UserRegistrationView,logout_view
urlpatterns = [
       path('admin/', admin.site.urls),
       path('',home, name='home'),
       path('reservation/', reservation_success ,name='reservation_success'),
       path('login/',UserLoginView.as_view(), name='login'),
       path('register/',UserRegistrationView.as_view(), name='register'),
       path('logout/',logout_view, name='logout'),
       path('manager/', include('manager.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import booking_data, booking_confirm


app_name = 'manager'

urlpatterns = [
    path('booking/', booking_data, name='booking'),
    path('booking/<int:pk>/', booking_confirm, name='booking_confirm'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from main.models import Reservation

def is_manager(user):
    return user.groups.filter(name='manager').exists() or user.is_superuser


# Create your views here.
@login_required(login_url='login')
@user_passes_test(is_manager)
def booking_data(request):
    data = Reservation.objects.filter(is_confirmed=False)
    context = {'items': data}
    return render(request, 'reservations.html', context=context)


def booking_confirm(request, pk):
    data = Reservation.objects.get(pk=pk)
    data.is_confirmed = True
    data.save()
    return redirect('manager:booking')

manager/templates/reservations.html
{% extends 'index.html' %}

{% block content %}
<section id="booking" class="booking">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2></h2>
            <p>Orders</p>
        </div>

        <ul class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="200">
            {% for category in categories %}
                {% if forloop.first %}
                    <li class="nav-item">
                        <a class="nav-link active show" data-bs-toggle="tab" data-bs-target="#menu-category-{{ category.pk }}">
                            <h4>{{ category.name }}</h4>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#menu-category-{{ category.pk }}">
                            <h4>{{ category.name }}</h4>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>

        <div class="tab-content" data-aos="fade-up" data-aos-delay="300">
            {% for item in items %}
                <div>
                    <div>{{ item.name }}</div>
                    <div>{{ item.email }}</div>
                    <div>{{ item.phone }}</div>
                    <div>{{ item.count }}</div>
                    <div>{{ item.message }}</div>
                    <div><a href="{% url 'manager:booking_confirm' item.pk %}">Confirm</a></div>

                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}